[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = "1"
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime" }
wit-bindgen-host-wasmtime-rust = { git = "https://github.com/bytecodealliance/wit-bindgen" }

[dev-dependencies]
test-programs-macros = { path = "../test-programs/macros" }
