[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = "1"
chrono = "0.4"
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime" }
wit-component = { git = "https://github.com/bytecodealliance/wit-bindgen" }
wit-bindgen-host-wasmtime-rust = { git = "https://github.com/bytecodealliance/wit-bindgen" }

